### ISSUE TITLE
License and contribution

### ISSUE THREAD

**Issue by ArturKovacs** [DashiellP/OohAFlowerTheme#1]
Hey! I'm loving the theme and would like to fix some colours, for example where there's white text on light background. 

In case you are okay with this could you add an MIT license or similar to allow me to make modifications. Many thanks 💙

**Comment by DashiellP** [comment]
Done! Feel free to do whatever you want with it

**Comment by ArturKovacs** [comment]
You are awesome!

One more question: do you prefer me to make PR for this repo so that you release the fixes, or should I make a new theme instead?

**Comment by DashiellP** [comment]
You can make a new theme if you want! I'm not really looking to maintain this and I'd want to make sure you get credit if you do

**Comment by ArturKovacs** [comment]
Awesome, thanks!
